name: "Shared Workflow"

on:
  workflow_call:
    inputs:
      ENVPREFIX:
        required: true
        type: string

jobs:
  run:
    env:
      ENVPREFIX: ${{ inputs.ENVPREFIX }}
    name: "Branch Deployment"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4    
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: projects/481994439242/locations/global/workloadIdentityPools/github-oidc-ts-infra-demo/providers/github-oidc-ts-infra-demo
          service_account: github-oidc@ts-infra-demo.iam.gserviceaccount.com
      - name: "build container"
        run: ci/build.sh
      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "gke-gcloud-auth-plugin"                  
      - name: "Deployment"
        run: ci/up.sh
            