name: "Build and run"

on:
  push:
    branches:
      - "master"

jobs:
  run:
    name: "Workload Identity Job"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4    
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: projects/481994439242/locations/global/workloadIdentityPools/github-oidc-ts-infra-demo/providers/github-oidc-ts-infra-demo
          service_account: github-oidc@ts-infra-demo.iam.gserviceaccount.com

      - name: "Docker login"
        run: |
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://europe-west4-docker.pkg.dev/ts-infra-demo/private

      - name: "build container"
        run: ENVPREFIX=demo ci/build.sh
      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "gke-gcloud-auth-plugin"                  
      - name: "Deployment"
        run: ENVPREFIX=demo ci/up.sh
            