name: Production Build and Deploy
# Strictly speaking this should occur on tag events so we can rollback and replay tags
on:
  push:
    branches:
      - master  

jobs:
  some-job:
    name: run the job
    uses: ./.github/workflows/build_deploy.yaml
    permissions:
        id-token: write
        contents: read    
    with:
      ENVPREFIX: "demo"